version: '3'
services:
  mysqldb:
    image: mysql:8.0.21
    container_name: express-demo-app-mysql
    restart: "no"
    environment:
      - MYSQL_DATABASE=demo-app
      - MYSQL_ROOT_PASSWORD=123456
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - '8989:3306'
    volumes:
      - './data/db/mysql:/var/lib/mysql'
  # postgres:
  #   image: postgres:latest
  #   container_name: express-demo-app-pgsql
  #   restart: "no"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123456
  #     PGPASSWORD: 123456
  #     POSTGRES_DB: demo-app
  #     TZ: "Asia/Shanghai PRC"
  #   ports:
  #     - 8988:5432
  #   volumes:
  #     - ./data/db/postgres:/var/lib/postgresql/data
